Repository spring-projects/spring-integration, pull requests merged in 2022-05, with the labels that each got.

#3806 Really reuse Testcontainers
  spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/mysql/MySqlContainerTest.java
  spring-integration-mqtt/src/test/java/org/springframework/integration/mqtt/MosquittoContainerTest.java
Labels: type: enhancement, in: testing, backport 5.5.x

#3810 Updated SMB Module Documentation For New Components
  src/reference/asciidoc/endpoint-summary.adoc
  src/reference/asciidoc/smb.adoc
  src/reference/asciidoc/whats-new.adoc
Labels: type: documentation

#3814 Improve Java DSL implementation and JUnit tests cases
  spring-integration-smb/src/main/java/org/springframework/integration/smb/session/SmbFileInfo.java
  spring-integration-smb/src/test/java/org/springframework/integration/smb/Main.java
  spring-integration-smb/src/test/java/org/springframework/integration/smb/dsl/SmbTests.java
  spring-integration-smb/src/test/java/org/springframework/integration/smb/inbound/SmbInboundRemoteFileSystemSynchronizerTests.java
  spring-integration-smb/src/test/resources/META-INF/spring/integration/spring-integration-context.xml
Labels: type: enhancement, in: smb
