Repository spring-projects/spring-integration, pull requests merged in 2024-10, with the labels that each got.

#9526 fix typos in distributed-locks.adoc
  src/reference/antora/modules/ROOT/pages/distributed-locks.adoc
Labels: type: documentation

#9546 Flag and maybe delete messages after messages have been copied
  spring-integration-mail/src/main/java/org/springframework/integration/mail/AbstractMailReceiver.java
  spring-integration-mail/src/test/java/org/springframework/integration/mail/ImapMailReceiverTests.java
Labels: type: bug, in: mail, for: backport-to-6.2.x, for: backport-to-6.3.x

#9556 Remove not used private variable from ImapIdleChannelAdapter
  spring-integration-mail/src/main/java/org/springframework/integration/mail/ImapIdleChannelAdapter.java
Labels: type: enhancement, in: mail

#9590 Update reactive-streams.adoc
  src/reference/antora/modules/ROOT/pages/reactive-streams.adoc
Labels: type: documentation

#9619 Improve readability of `delete` and `renew` methods of DefaultLockRepository
  spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java
Labels: type: refactoring, in: redis
